<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-JEVDLHC" failures="1" tests="1" name="ieTest" time="45.931" errors="0" timestamp="2021-06-14T11:18:24 IST">
  <testcase classname="testCases.ReviewPageTest" name="ratingReviewTest" time="16.591">
    <failure type="java.lang.AssertionError" message="expected [Excellent1] but found [Excellent]">
      <![CDATA[java.lang.AssertionError: expected [Excellent1] but found [Excellent]
at testCases.ReviewPageTest.ratingReviewTest(ReviewPageTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- ratingReviewTest -->
</testsuite> <!-- ieTest -->
